### ISSUE TITLE
--ratio options v6.2.1 not working properly

### ISSUE THREAD

**Issue by Shikakka** [elastic/spritezero#7]
After updating to the latest version, v6.2.1, I am encountering a problem with generating the --ratio files. It only happens when using the --sdf option.

If and when I have some spare time left. I will look in to it, but I don't know when that will be. You might want to fix it before that happens :) 

I am using the cli with command:
`spritezero sprite@4x ./svg --sdf --ratio=4`

**v6.2.0**
![v6 2 0 @4x](https://user-images.githubusercontent.com/7727784/83238938-6aabd080-a197-11ea-91c6-c60ace5ce6d2.png)

**v6.2.1**
![v6 2 1@4x](https://user-images.githubusercontent.com/7727784/83238942-6b446700-a197-11ea-8b18-a5effe8c3ad5.png)

after downgrading back to v6.2.0 everything works again.

**Comment by PMeira** [comment]
I also hit the issue. Since the code is not that complex, I looked into it and the noticed the error only happens when the SVG has a `viewBox` set.

By the time the viewBox info is checked, `h`, `w` and `svgPath` are already scaled by `options.pixelRatio`, so it's scaled by one extra `options.pixelRatio` here:

https://github.com/elastic/spritezero/blob/3b89dc0fef2acbf9db1e77a753a68b02f74939a8/index.js#L170-L174

A trivial solution would be to use on line 173:
```
.scale((w/options.pixelRatio)/(viewBox[2] - viewBox[0]), (h/options.pixelRatio)/(viewBox[3] - viewBox[1]));
```

A more elegant solution would be to save the original `w` and `h` before multiplying by `options.pixelRatio`.
